import source from '../../reference/late-goblin-buildings/combat.json';
import type { Building } from './model';
import type { WeaponProfile } from './late-goblin-weapon';

/** Pinned client 18.400.21 rows, generated by scripts/import-native-late-goblin-buildings.py. */
export const LATE_GOBLIN_SOURCE = source;
export type LateGoblinIdentity =
  'comm-mast' | 'goblin-hall' | 'goblin-castle' | 'foreboding-cave' | 'goblin-boss-th';
export const isLateGoblinIdentity = (value: unknown): value is LateGoblinIdentity =>
  typeof value === 'string' && Object.hasOwn(source.identities, value);
export type GoblinWeaponKind = 'goblin-hall' | 'goblin-boss-th';
export interface GoblinWeapon extends WeaponProfile {
  kind: GoblinWeaponKind;
  level: number;
  damage: number;
  /** Distinct simultaneous targets. A multi-target row without NumMultiTargets keeps one. */
  slots: number;
  /** Ground splash radius in tiles, from the building row's DamageRadius. */
  splash: number;
  projectileSpeed: number;
  tracking: boolean;
  activateOnDamage: boolean;
  activationDelay: number;
  source: (typeof source.weapons)[GoblinWeaponKind];
}
const weapon = (kind: GoblinWeaponKind): GoblinWeapon => {
  const row = source.weapons[kind];
  return {
    kind,
    level: row.level,
    range: row.rangeSource / 100,
    intervalMs: row.intervalMs,
    air: row.airTargets,
    ground: row.groundTargets,
    damage: row.damagePerHit,
    slots: row.multiTargets && row.numMultiTargets > 0 ? row.numMultiTargets : 1,
    splash: row.damageRadiusSource / 100,
    projectileSpeed: row.projectileSpeed / 100,
    tracking: row.tracking,
    activateOnDamage: row.activateOnDamage,
    activationDelay: row.activationDelayMs / 1000,
    source: row,
  };
};
export const GOBLIN_WEAPONS: Readonly<Record<GoblinWeaponKind, GoblinWeapon>> = {
  'goblin-hall': weapon('goblin-hall'),
  'goblin-boss-th': weapon('goblin-boss-th'),
};
/** Goblin Hall level 1 has no weapon; its level 2 and the Boss Town Hall carry one. */
export function goblinWeaponFor(b: Pick<Building, 'npc' | 'level'>) {
  if (b.npc === 'goblin-hall' && b.level === GOBLIN_WEAPONS['goblin-hall'].level)
    return GOBLIN_WEAPONS['goblin-hall'];
  if (b.npc === 'goblin-boss-th' && b.level === GOBLIN_WEAPONS['goblin-boss-th'].level)
    return GOBLIN_WEAPONS['goblin-boss-th'];
  return undefined;
}
export interface GoblinBuildingArt {
  body: string;
  base: string;
  ruin: string;
  destroyEffect: string;
  size: number;
  anchor: readonly number[];
}
/** Source body/base/ruin exports; weapon-bearing halls display their weapon export. */
export function goblinBuildingArt(npc: LateGoblinIdentity, level: number): GoblinBuildingArt {
  const identity = source.identities[npc];
  const row = 'levels' in identity ? identity.levels[level - 1] : identity;
  if (!row) throw Error(`Unsupported ${npc} level: ${level}`);
  const armed = goblinWeaponFor({ npc, level });
  return { ...row, body: armed ? armed.source.export : row.body };
}
export const GOBLIN_TIMELINE = source.timeline;
export const GOBLIN_CAVE_TIMELINE = source.caveTimeline;
export const HIDDEN_BUILDING_APPEAR_PERCENT = source.hiddenBuildingAppearDestructionPercentage;
