import { describe, it, expect } from 'vitest';
import { GameModel, makeBuilding } from '../src/game/model';
import { MAX_TROOP_LEVEL, TROOPS } from '../src/game/data';
import { validateSave } from '../src/game/save';
describe('troop progression', () => {
  it('research is gated by laboratory level, charged once and completes offline once', () => {
    const m = new GameModel(),
      lab = m.state.buildings.find((b) => b.kind === 'laboratory')!;
    lab.level = 1;
    const elixir = m.state.elixir;
    m.researchTroop('giant');
    expect(m.state.research).toBeUndefined();
    expect(m.state.elixir).toBe(elixir);
    lab.level = 2;
    m.researchTroop('giant');
    expect(m.state.elixir).toBe(elixir - 12000);
    m.researchTroop('archer');
    expect(m.state.elixir).toBe(elixir - 12000);
    m.upgrade(lab.id);
    expect(lab.upgradeEnd).toBeUndefined();
    expect(validateSave(m.state)).toBe(true);
    const restored = new GameModel(structuredClone(m.state));
    restored.tick(restored.state.research!.end + 8 * 3600000);
    expect(restored.troopLevel('giant')).toBe(2);
    expect(restored.state.research).toBeUndefined();
    restored.tick(restored.clock + 999999);
    expect(restored.troopLevel('giant')).toBe(2);
    restored.startBattle(0);
    restored.activeTroop = 'giant';
    restored.deploy(1, 13);
    expect(restored.battle!.units[0].maxHp).toBe(Math.round(TROOPS.giant.hp * 1.3));
    expect(restored.troopStats('giant').damage).toBe(Math.round(TROOPS.giant.damage * 1.3));
  });
  it('finishes research with gems and refuses malformed or over-level research saves', () => {
    const m = new GameModel();
    m.state.buildings.find((b) => b.kind === 'laboratory')!.level = 3;
    const gems = m.state.gems;
    m.researchTroop('archer');
    m.finishResearch();
    expect(m.state.gems).toBe(gems - 3);
    expect(m.troopLevel('archer')).toBe(2);
    expect(validateSave(m.state)).toBe(true);
    m.state.troopLevels!.archer = MAX_TROOP_LEVEL + 1;
    expect(validateSave(m.state)).toBe(false);
    m.state.troopLevels!.archer = MAX_TROOP_LEVEL;
    m.state.research = { kind: 'archer', end: m.clock };
    expect(validateSave(m.state)).toBe(false);
    delete m.state.research;
    delete m.state.troopLevels;
    expect(validateSave(m.state)).toBe(true);
  });
  it('batch training is atomic and retraining only fills missing troops', () => {
    const m = new GameModel();
    const initial = { ...m.state.army };
    const elixir = m.state.elixir;
    m.train('giant', 5);
    expect(m.state.queue).toHaveLength(0);
    expect(m.state.elixir).toBe(elixir);
    m.startBattle(0);
    m.activeTroop = 'archer';
    for (let i = 0; i < 5; i++) m.deploy(1, 13);
    m.finishBattle();
    m.returnHome();
    m.train('archer', 1);
    m.retrain();
    expect(m.state.queue).toHaveLength(0);
    expect(m.state.army).toEqual(initial);
    expect(m.state.elixir).toBe(elixir);
    m.retrain();
    expect(m.state.queue).toHaveLength(0);
    expect(m.state.army).toEqual(initial);
    m.tick(m.clock + 60000);
    expect(m.state.army).toEqual(initial);
  });
  it('requires a completed barracks, with no training timer', () => {
    const m = new GameModel();
    for (const b of m.state.buildings.filter((b) => b.kind === 'barracks')) b.upgradeEnd = m.clock + 100000;
    const before = m.state.army.archer;
    m.train('archer');
    expect(m.state.army.archer).toBe(before);
    const b = makeBuilding(m.state.nextId++, 'barracks', 1, 1);
    b.constructing = true; m.state.buildings.push(b);
    m.train('archer');
    expect(m.state.army.archer).toBe(before);
    b.constructing = false;
    m.train('archer');
    expect(m.state.army.archer).toBe(before + 1);
    expect(m.state.queue).toEqual([]);
  });
});
