// Generates the offline service worker for a production build.
//
// Only the application shell (HTML, the JS/CSS bundles and the favicon) is
// precached, and a failed shell download fails the install so the previous
// complete cache keeps serving. The art a player's boot actually used is sent
// by the page (see src/offline.ts) and cached best-effort before activation;
// everything else is cached the first time it is fetched. Every build file has
// a content hash in the manifest, so an update copies unchanged files from the
// previous cache instead of downloading them again.
//
// Usage: node scripts/build-sw.mjs [distDir]
import fs from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';

const dist = process.argv[2] ?? 'dist';

async function walk(dir) {
  const result = [];
  for (const entry of await fs.readdir(dir, { withFileTypes: true })) {
    const p = path.join(dir, entry.name);
    if (entry.isDirectory()) result.push(...(await walk(p)));
    else result.push(p);
  }
  return result;
}
const toUrl = (file) => '/' + path.relative(dist, file).split(path.sep).join('/');

// Drop the output of an earlier run so it is neither hashed nor listed.
for (const file of await fs.readdir(dist))
  if (file === 'sw.js' || /^sw-manifest\.[0-9a-f]+\.json$/.test(file))
    await fs.rm(path.join(dist, file));

const hashes = {};
let totalBytes = 0;
for (const file of (await walk(dist)).sort()) {
  const bytes = await fs.readFile(file);
  totalBytes += bytes.length;
  hashes[toUrl(file)] = crypto.createHash('sha256').update(bytes).digest('hex').slice(0, 16);
}
// Navigations to the root are served by index.html.
hashes['/'] = hashes['/index.html'];

// The shell: the page, the Vite bundles at the top of /assets (fonts load at
// runtime and are warmed with the boot set) and root-level static files other
// than the developer asset catalog.
const shell = Object.keys(hashes)
  .filter(
    (url) =>
      url === '/' ||
      url === '/index.html' ||
      /^\/assets\/[^/]+\.(?:js|css)$/.test(url) ||
      (/^\/[^/]+$/.test(url) && url !== '/asset-catalog.html'),
  )
  .sort();
let shellBytes = 0;
for (const url of shell) if (url !== '/') shellBytes += (await fs.stat(path.join(dist, url))).size;

const version = crypto
  .createHash('sha256')
  .update(JSON.stringify(hashes))
  .digest('hex')
  .slice(0, 12);
const manifestUrl = `/sw-manifest.${version}.json`;
await fs.writeFile(path.join(dist, manifestUrl.slice(1)), JSON.stringify(hashes));

const worker = `// Generated by scripts/build-sw.mjs; do not edit.
const VERSION = ${JSON.stringify(version)};
const CACHE = 'crown-clan-' + VERSION;
const MANIFEST_URL = ${JSON.stringify(manifestUrl)};
const MANIFEST_KEY = '/__crown-sw-manifest';
const SHELL = ${JSON.stringify(shell)};
const BOOT_LIST_WAIT = 3000;

let manifest;
/** url -> content hash for every build file; stored in the cache by a completed install. */
async function loadManifest() {
  if (manifest) return manifest;
  const hit = await caches.match(MANIFEST_KEY, { cacheName: CACHE }).catch(() => undefined);
  if (hit) manifest = await hit.json();
  return manifest ?? {};
}
/** True only while this worker's install runs (a restarted worker starts false). */
let installing = false;

const hex = (buffer) =>
  Array.from(new Uint8Array(buffer), (b) => b.toString(16).padStart(2, '0')).join('');
/**
 * Fetches a build file and, given its manifest hash, checks the bytes: a host
 * rewrite (index.html for a missing path) or a half-finished deploy must not be
 * stored under this version.
 */
async function download(url, expected) {
  // Revalidate: unhashed art may sit in the HTTP cache from before the deploy.
  const response = await fetch(url, { cache: 'no-cache' });
  if (!response.ok || response.type !== 'basic') throw new Error(url + ': ' + response.status);
  if (!expected) return response;
  const bytes = await response.arrayBuffer();
  const actual = hex(await crypto.subtle.digest('SHA-256', bytes)).slice(0, expected.length);
  if (actual !== expected) throw new Error(url + ': content does not match this version');
  return new Response(bytes, {
    status: response.status,
    statusText: response.statusText,
    headers: response.headers,
  });
}
async function inBatches(items, size, task) {
  for (let i = 0; i < items.length; i += size) await Promise.all(items.slice(i, i + size).map(task));
}
/** Best-effort: files the page already loaded, limited to build files not cached yet. */
async function warm(cache, hashes, urls) {
  const wanted = [...new Set(urls)].filter((url) => hashes[url]);
  let added = 0;
  await inBatches(wanted, 4, async (url) => {
    if (await cache.match(url)) return;
    try {
      await cache.put(url, await download(url, hashes[url]));
      added++;
    } catch {
      /* Fetched again (and cached) the next time the game asks for it. */
    }
  });
  return added;
}

// The registering page posts the files its boot used; the install waits briefly for them
// so the first offline reload has its art even if the network drops right after install.
let receiveBootList;
const bootList = new Promise((resolve) => (receiveBootList = resolve));

self.addEventListener('install', (event) => {
  installing = true;
  event.waitUntil(
    (async () => {
      const hashes = await (await download(MANIFEST_URL)).json();
      const cache = await caches.open(CACHE);
      // Copy every file whose content is unchanged from earlier versions' caches.
      for (const name of await caches.keys()) {
        if (name === CACHE || !name.startsWith('crown-clan-')) continue;
        const old = await caches.open(name);
        const previous = await old.match(MANIFEST_KEY);
        if (!previous) continue;
        const oldHashes = await previous.json();
        for (const request of await old.keys()) {
          const url = new URL(request.url).pathname;
          if (!hashes[url] || oldHashes[url] !== hashes[url] || (await cache.match(url))) continue;
          const response = await old.match(request);
          if (response) await cache.put(url, response);
        }
      }
      // The shell is required: any failure rejects the install and the previous
      // worker and its complete cache stay in charge.
      await inBatches(SHELL, 6, async (url) => {
        if (!(await cache.match(url))) await cache.put(url, await download(url, hashes[url]));
      });
      const urls = await Promise.race([
        bootList,
        new Promise((resolve) => setTimeout(() => resolve([]), BOOT_LIST_WAIT)),
      ]);
      await warm(cache, hashes, urls);
      await cache.put(
        MANIFEST_KEY,
        new Response(JSON.stringify(hashes), { headers: { 'content-type': 'application/json' } }),
      );
      manifest = hashes;
    })()
      .catch(async (error) => {
        // Leave no half-filled cache behind; the previous version keeps serving.
        await caches.delete(CACHE);
        throw error;
      })
      .finally(() => {
        installing = false;
      }),
  );
  self.skipWaiting();
});

self.addEventListener('activate', (event) =>
  event.waitUntil(
    caches
      .keys()
      .then((keys) =>
        Promise.all(
          keys.filter((k) => k.startsWith('crown-clan-') && k !== CACHE).map((k) => caches.delete(k)),
        ),
      )
      .then(() => self.clients.claim()),
  ),
);

self.addEventListener('message', (event) => {
  const data = event.data;
  if (!data || data.type !== 'warm' || !Array.isArray(data.urls)) return;
  const urls = data.urls.filter((url) => typeof url === 'string');
  // During (or just before) this worker's install, the list feeds the install's warm-up.
  receiveBootList(urls);
  if (installing) return;
  event.waitUntil(
    (async () => {
      const cache = await caches.open(CACHE);
      const added = await warm(cache, await loadManifest(), urls);
      event.source?.postMessage({ type: 'warmed', version: VERSION, added });
    })(),
  );
});

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;
  if (request.mode === 'navigate') {
    event.respondWith(
      fetch(request).catch(async () => (await caches.match('/index.html', { ignoreVary: true })) ?? Response.error()),
    );
    return;
  }
  event.respondWith(
    (async () => {
      const cache = await caches.open(CACHE);
      const hit = await cache.match(request, { ignoreVary: true });
      if (hit) return hit;
      const response = await fetch(request);
      // Cache-first for build files: fetched once, then served offline.
      if (
        response.status === 200 &&
        response.type === 'basic' &&
        !request.headers.has('range') &&
        !url.search &&
        (await loadManifest())[url.pathname]
      )
        event.waitUntil(cache.put(url.pathname, response.clone()).catch(() => {}));
      return response;
    })(),
  );
});
`;
await fs.writeFile(path.join(dist, 'sw.js'), worker);
const mb = (bytes) => `${(bytes / 1048576).toFixed(1)} MB`;
console.log(
  `Offline shell: ${shell.length} files, ${mb(shellBytes)} precached; ` +
    `${Object.keys(hashes).length - 1} files (${mb(totalBytes)}) hashed for runtime caching; cache crown-clan-${version}`,
);
