/**
 * Offline support for production builds (worker generated by scripts/build-sw.mjs).
 *
 * The worker precaches only the application shell. The art this page's boot
 * actually downloaded is listed from Resource Timing and posted to the worker,
 * which caches it best-effort (during its first install, before it activates),
 * so an offline reload finds everything the boot needs without every player
 * downloading the whole art library.
 */

/** Resource Timing drops entries past its buffer (250 by default); the boot loads more. */
export function recordBootResources() {
  try {
    performance.setResourceTimingBufferSize(4000);
  } catch {
    /* Older engines keep the default buffer. */
  }
}

function loadedPaths() {
  const paths = new Set<string>();
  for (const entry of performance.getEntriesByType('resource')) {
    try {
      const url = new URL(entry.name);
      if (url.origin === location.origin && !url.search) paths.add(url.pathname);
    } catch {
      /* Not a URL. */
    }
  }
  return [...paths];
}

/**
 * What offline play can rely on right now: 'unsupported' (no service worker, or a development
 * page), 'preparing' until the worker has stored this page's boot art, 'ready' once it has, or
 * 'partial' when some of that art could not be stored (a retry is offered).
 */
export type OfflineStatus = 'unsupported' | 'preparing' | 'ready' | 'partial';
let status: OfflineStatus = 'unsupported';
let onStatus: (status: OfflineStatus) => void = () => {};
export const offlineStatus = () => status;
/** The HUD redraws its Settings note when the status changes. */
export function watchOfflineStatus(listener: (status: OfflineStatus) => void) {
  onStatus = listener;
}
function setStatus(next: OfflineStatus) {
  status = next;
  document.documentElement.dataset.offline = next;
  onStatus(next);
}
/** Asks the active worker to store this page's art again (after a partial warm-up). */
export function retryOfflineWarm() {
  const worker = 'serviceWorker' in navigator ? navigator.serviceWorker.controller : null;
  if (!worker) return;
  setStatus('preparing');
  worker.postMessage({ type: 'warm', urls: loadedPaths() });
}

const idle = (callback: () => void) =>
  'requestIdleCallback' in window
    ? requestIdleCallback(callback, { timeout: 4000 })
    : setTimeout(callback, 1000);

/**
 * Registers the worker once the village is on screen and the browser is idle, so
 * the install never competes with the boot preload for bandwidth.
 */
export function registerOfflineSupport() {
  // A lazy chunk that no longer exists on the host (a deploy landed while this page was open
  // and no worker served it from cache) is fatal to the page in every other way; reload onto
  // the new version. The unload path settles any battle and stores the village first.
  window.addEventListener('vite:preloadError', (event) => {
    event.preventDefault();
    window.location.reload();
  });
  if (!('serviceWorker' in navigator)) return;
  setStatus('preparing');
  const container = navigator.serviceWorker;
  const post = (worker: ServiceWorker | null | undefined) =>
    worker?.postMessage({ type: 'warm', urls: loadedPaths() });
  container.addEventListener('message', (event: MessageEvent) => {
    if (event.data?.type === 'warmed') setStatus(event.data.failed ? 'partial' : 'ready');
  });
  let updating = false;
  // Files fetched before this page came under the worker's control never passed
  // through it; list them again once it takes over. An update the player accepted
  // reloads the page onto the release its new worker serves.
  container.addEventListener('controllerchange', () => {
    if (updating) window.location.reload();
    else post(container.controller);
  });
  idle(() => {
    container
      .register('/sw.js')
      .then((registration) => {
        post(registration.installing ?? container.controller);
        // Pages stay on the release their worker serves; a newer one waits until offered.
        const offer = () => {
          const waiting = registration.waiting;
          if (!waiting || !container.controller) return;
          offerUpdate(() => {
            updating = true;
            waiting.postMessage({ type: 'activate-update' });
          });
        };
        offer();
        registration.addEventListener('updatefound', () => {
          const next = registration.installing;
          next?.addEventListener('statechange', () => {
            if (next.state === 'installed') offer();
          });
        });
      })
      .catch((error) => console.warn(error));
  });
}

/** A small prompt to reload onto a downloaded update; the village is saved on unload. */
function offerUpdate(accept: () => void) {
  if (document.getElementById('update-ready')) return;
  const prompt = document.createElement('button');
  prompt.id = 'update-ready';
  prompt.type = 'button';
  prompt.textContent = 'Update ready · Reload';
  prompt.addEventListener('click', () => {
    prompt.disabled = true;
    accept();
  });
  document.body.append(prompt);
}
