/**
 * Offline support for production builds (worker generated by scripts/build-sw.mjs).
 *
 * The worker precaches only the application shell. The art this page's boot
 * actually downloaded is listed from Resource Timing and posted to the worker,
 * which caches it best-effort (during its first install, before it activates),
 * so an offline reload finds everything the boot needs without every player
 * downloading the whole art library.
 */

/** Resource Timing drops entries past its buffer (250 by default); the boot loads more. */
export function recordBootResources() {
  try {
    performance.setResourceTimingBufferSize(4000);
  } catch {
    /* Older engines keep the default buffer. */
  }
}

function loadedPaths() {
  const paths = new Set<string>();
  for (const entry of performance.getEntriesByType('resource')) {
    try {
      const url = new URL(entry.name);
      if (url.origin === location.origin && !url.search) paths.add(url.pathname);
    } catch {
      /* Not a URL. */
    }
  }
  return [...paths];
}

const idle = (callback: () => void) =>
  'requestIdleCallback' in window
    ? requestIdleCallback(callback, { timeout: 4000 })
    : setTimeout(callback, 1000);

/**
 * Registers the worker once the village is on screen and the browser is idle, so
 * the install never competes with the boot preload for bandwidth.
 */
export function registerOfflineSupport() {
  // A lazy chunk that no longer exists on the host (a deploy landed while this page was open
  // and no worker served it from cache) is fatal to the page in every other way; reload onto
  // the new version. The unload path settles any battle and stores the village first.
  window.addEventListener('vite:preloadError', (event) => {
    event.preventDefault();
    window.location.reload();
  });
  if (!('serviceWorker' in navigator)) return;
  const container = navigator.serviceWorker;
  const post = (worker: ServiceWorker | null | undefined) =>
    worker?.postMessage({ type: 'warm', urls: loadedPaths() });
  container.addEventListener('message', (event: MessageEvent) => {
    if (event.data?.type === 'warmed') document.documentElement.dataset.offline = 'ready';
  });
  // Files fetched before this page came under the worker's control never passed
  // through it; list them again once it takes over.
  container.addEventListener('controllerchange', () => post(container.controller));
  idle(() => {
    container
      .register('/sw.js')
      .then((registration) => post(registration.installing ?? container.controller))
      .catch((error) => console.warn(error));
  });
}
